### ISSUE TITLE
App sorting seems incorrect

### ISSUE THREAD

**Issue by funglaub** [errbit/errbit#973]
I'm using errbit from the current master and the sorting of all apps by the unresolved count seems to be wrong: apps with the highest unresolved count appear somewhere in the middle or at the end of the list. The first item has an unresolved error count of 0.

Is this a bug or did I miss something when upgrading?

**Comment by stevecrozz** [comment]
Yeah this was my mistake and I just realized it. We had another user @lucianosousa who wanted apps to be sorted differently: https://github.com/errbit/errbit/pull/924

And I didn't understand the intent at the time, but I ran across the answer it a few days ago in how it used to work: https://github.com/errbit/errbit/blob/v0.4.0/app/models/app.rb#L179-L184

We apparently have conflicting desires about how apps should be sorted and I don't really want to introduce fancy per-column sorting at this time. I'm inclined to revert #924 now that I understand what happened.

On the other hand, this is the first complaint I've heard about the new sorting method. Is this new method a problem for you @funglaub ?

**Comment by lucianosousa** [comment]
what I did was just sort by name.
my problem before it was:
I've a lot of apps with different envs, eg: [ app acceptance, app staging, app production]

to find the errors in these apps, I scroll a lot(sometimes, command + f plus app name).
now, I've this set of apps together, and looks easier to me.
---
@stevecrozz, this sort per column function looks interesting. at the first time using the app, I was looking for it.

**Comment by funglaub** [comment]
Well this is rather a a matter of taste than being a real problem. I created this issue since I noticed the behaviour changed after I updated.

@lucianosousa's point makes sense too. But for me it's more imported to see what's actually having unresolved errors in a long project list :) How about making this option configurable at `/site_config`?

**Comment by lucianosousa** [comment]
Too much options. I think the best approach will be some kind of table sort(per column)

**Comment by stevecrozz** [comment]
Yeah maybe table column sorting is the best option. Of course as soon as we add that, the next feature will be to persist your column sorting preference. My current thinking is to restore the old behavior of sorting apps by unresolved error count. Then we can add a story about per-column sorting.

**Comment by lucianosousa** [comment]
https://github.com/errbit/errbit/commit/644116d884df846f633ee0d213fab94138e80465

```
$ git revert 644116d884df846f633ee0d213fab94138e80465
```

will fix it

**Comment by funglaub** [comment]
I'm fine with that, too

**Comment by stevecrozz** [comment]
Fixed with https://github.com/errbit/errbit/commit/b1fe739a5bf829913d37e7ed0c2f5fb701e67b5d

More discussion to come in https://github.com/errbit/errbit/issues/975

**Comment by funglaub** [comment]
I just pulled from master and it's still not sorting by error count (and neither by name, somehow just random). Did I miss something?

**Comment by funglaub** [comment]
Did you possibly forget to change https://github.com/errbit/errbit/blob/v0.4.0/app/models/app.rb#L179-L184 as mentioned in your [comment](https://github.com/errbit/errbit/issues/973#issuecomment-148785871)?

**Comment by stevecrozz** [comment]
It appears to be here: https://github.com/errbit/errbit/blob/master/app/models/app.rb#L177-L181 in master.

**Comment by md5** [comment]
I just came across this change in `v0.5.0` after I upgraded today from an intermediate SHA between `v0.4.0` and `v0.5.0`. I'm seeing the apps sorted by their `id`, not by unresolved error count.

What is the expected sorting behavior now?

**Comment by md5** [comment]
I see the code for this here: https://github.com/errbit/errbit/blob/14c71aa4aa61080eda91e3dd0fbabb87332d0a68/app/models/app.rb#L172-L177

Perhaps I'm wrong about how it's sorting and it's actually sorting by `problem_count` (since our apps currently have no unresolved errors)...

**Comment by stevecrozz** [comment]
Yep. I was just hunting for that but you found it first. That is how it is supposed to sort at the moment.

**Comment by md5** [comment]
I see the problem. `App.all.sort` is not using `<=>` since `#sort` is defined by Mongoid.

**Comment by md5** [comment]
To use `<=>`, it would have to do a `to_a` first, i.e. `App.all.to_a.sort`.

**Comment by md5** [comment]
@stevecrozz Do you want me to open a new issue for this or provide a PR that changes to `App.all.to_a.sort`?

**Comment by stevecrozz** [comment]
PR is great because I can click and be done, but either way works. Thanks very much for spotting the issue.

**Comment by md5** [comment]
Opened https://github.com/errbit/errbit/pull/1016
